### ISSUE TITLE
FOSUserBundle

### ISSUE THREAD

**Issue by martinbobbio** [martinbobbio/davinci-tennisstar-backend#2]
Integrar FOSUserBundle para el login y registro de usuarios en el frontend y el backend

https://symfony.com/doc/master/bundles/FOSUserBundle/index.html

**Comment by PapoMage** [comment]
Integracion completa de FOSUserBundle, solucion al problema eliminando una dependencia de PHP en composer.json.

**Comment by martinbobbio** [comment]
Login y registro con FOSUser
